/*
 * This file is generated by jOOQ.
*/
package pl.jdata.samples.jooqsample.jooqmodel;


import javax.annotation.Generated;

import pl.jdata.samples.jooqsample.jooqmodel.tables.SystemUser;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.system_user</code>.
     */
    public static final SystemUser SYSTEM_USER = pl.jdata.samples.jooqsample.jooqmodel.tables.SystemUser.SYSTEM_USER;
}
