/*
 * This file is generated by jOOQ.
*/
package pl.jdata.samples.jooqsample.jooqmodel.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import pl.jdata.samples.jooqsample.jooqmodel.Keys;
import pl.jdata.samples.jooqsample.jooqmodel.Public;
import pl.jdata.samples.jooqsample.jooqmodel.tables.records.SystemUserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemUser extends TableImpl<SystemUserRecord> {

    private static final long serialVersionUID = -929912668;

    /**
     * The reference instance of <code>public.system_user</code>
     */
    public static final SystemUser SYSTEM_USER = new SystemUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemUserRecord> getRecordType() {
        return SystemUserRecord.class;
    }

    /**
     * The column <code>public.system_user.id</code>.
     */
    public final TableField<SystemUserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.system_user.username</code>.
     */
    public final TableField<SystemUserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

    /**
     * Create a <code>public.system_user</code> table reference
     */
    public SystemUser() {
        this("system_user", null);
    }

    /**
     * Create an aliased <code>public.system_user</code> table reference
     */
    public SystemUser(String alias) {
        this(alias, SYSTEM_USER);
    }

    private SystemUser(String alias, Table<SystemUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemUser(String alias, Table<SystemUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SystemUserRecord> getPrimaryKey() {
        return Keys.PK_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SystemUserRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemUserRecord>>asList(Keys.PK_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemUser as(String alias) {
        return new SystemUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUser rename(String name) {
        return new SystemUser(name, null);
    }
}
